controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.44 # distance between wheels ${ly/2+le_w/2}*2
    wheel_radius: 0.05
    enable_odom_tf: false

    # === Parámetros para suavizar el movimiento y eitar derrapes ===
    # Evita que el robot "salte" o haga "caballitos" al hacer cambios bruscos de atras hacia adelante o viceversa
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 5.0        # m/s
        has_acceleration_limits: true
        max_acceleration: 1.5    # m/s^2 
        
    # Evita giros bruscos que marean la odometría
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0        # rad/s
        has_acceleration_limits: true
        max_acceleration: 4.0    # rad/s^2